DROP DATABASE IF EXISTS sports;
CREATE DATABASE sports;

USE sports;

DROP TABLE IF EXISTS players;
CREATE TABLE players(
id INT AUTO_INCREMENT,
username VARCHAR(50),
pass VARCHAR(150),
firstName VARCHAR(50),
lastName VARCHAR(50),
email VARCHAR(50),
cellPhone VARCHAR(20),
homePhone VARCHAR(20),
address VARCHAR(50),
city VARCHAR(50),
state VARCHAR(20),
zip VARCHAR(20),
highschool VARCHAR(50),
weight CHAR(10),
height CHAR(10),
gradYear char(4),
sport VARCHAR(100),
primaryPosition VARCHAR(20),
secondaryPosition VARCHAR(20),
travelTeam VARCHAR(20),
gpa VARCHAR(5),
sat VARCHAR(5),
act VARCHAR(5),
ref1FirstName VARCHAR(50),
ref1LastName  VARCHAR(50),
ref1JobTitle  VARCHAR(50),
ref1Email  VARCHAR(50),
ref1Phone  VARCHAR(50),
ref2FirstName VARCHAR(50),
ref2LastName VARCHAR(50),
ref2JobTitle VARCHAR(50),
ref2Email VARCHAR(50),
ref2Phone VARCHAR(50),
ref3FirstName VARCHAR(50),
ref3LastName VARCHAR(50),
ref3JobTitle VARCHAR(50),
ref3Email VARCHAR(50),
ref3Phone VARCHAR(50),
PersStatement VARCHAR(150), 
service VARCHAR(50),
CONSTRAINT pk_users PRIMARY KEY(id)
);

INSERT INTO players(username, pass, firstName, lastName, email, cellPhone, homePhone, address, city, state, zip, highschool, weight, height, gradYear, sport, primaryPosition, secondaryPosition, travelTeam, gpa, sat, act, ref1FirstName, ref1LastName, ref1JobTitle, ref1Email, ref1Phone, ref2FirstName, ref2LastName, ref2JobTitle, ref2Email, ref2Phone, ref3FirstName, ref3LastName, ref3JobTitle, ref3Email, ref3Phone, PersStatement, service
)
VALUES(
'dmoore',
'1234',
'Dale',
'Moore',
'dmoore092@gmail.com',
'5551212',
'5551111',
'123 Sesame Street',
'Rochester',
'New York',
'14586',
'Rochester High School',
'220',
'510',
'1998',
'Baseball',
'1st base',
'2nd Base',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
NULL
);